### ISSUE TITLE
Roadmap for working release

### ISSUE THREAD

**Issue by nathankot** [nathankot/company-sourcekit#2]
@terhechte as per #1, here's a list of things I think need to be done. Feel free to edit at will.
- [x] Clean up useless `-project` and `-workspace` flags, via #3
- [x] Ensure vanilla completion is working without project support, via #3
- [x] Ensure completion function is async (currently not), via #3
- [x] Annotations and type information when displaying candidates, via #3
- [x] Typing after completion candidates are built should instantly narrow down results, via #5
- [x] Add project support via `--compilerargs`, see #4
- [x] Write readme!
- [x] Keep XPC running? Might be nice if sourcekitten can run as daemon, see https://github.com/terhechte/SourceKittenDaemon

For project support we can simply check for common cocoapods/carthage framework paths and add them with `-F`. `-sdk` and `-target` detection might be more involving...
